/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package logutils;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertIterableEquals;

class TimedLogsTest {

  @Test
  void testSomeLibraryMethod() {
    List<TimedLogEntry> logEntries = Arrays.asList(
            new TimedLogEntry("log one", 1),
            new TimedLogEntry("log two", 2),
            new TimedLogEntry("log three", 3),
            new TimedLogEntry("log four", 4),
            new TimedLogEntry("log five", 5),
            new TimedLogEntry("log five", 6)
    );

    TimedLogs timedLogs = new TimedLogs(logEntries);

    List<TimedLogEntry> expected = Arrays.asList(
      new TimedLogEntry("log three", 3),
      new TimedLogEntry("log four", 4)
    );

    List<TimedLogEntry> uniqueLogEntries = timedLogs.getLogEntriesBetween(3L, 5L);

    assertIterableEquals(expected, uniqueLogEntries);
  }
}
