/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package logutils;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertIterableEquals;

class UniqueLogsTest {

  private UniqueLogs uniqueLogs;

  @BeforeEach
  void setUp() {
    uniqueLogs = new UniqueLogs();
  }

  @Test
  void testSomeLibraryMethod() {

    List<LogEntry> logEntries = Arrays.asList(
      new LogEntry("log one"),
      new LogEntry("log one"),
      new LogEntry("log two"),
      new LogEntry("log three"),
      new LogEntry("log three"),
      new LogEntry("log four"),
      new LogEntry("log five"),
      new LogEntry("log five")
    );

    List<LogEntry> expected = Arrays.asList(
      new LogEntry("log one"),
      new LogEntry("log two"),
      new LogEntry("log three"),
      new LogEntry("log four"),
      new LogEntry("log five")
    );

    List<LogEntry> uniqueLogEntries = uniqueLogs.getUniqueLogEntries(logEntries);

    assertIterableEquals(expected, uniqueLogEntries);
  }
}
